language: go
sudo: false
go:
- 1.11
before_install:
- go get github.com/spf13/cobra
jobs:
  include:
  - script: make all
    deploy:
      provider: releases
      skip_cleanup: true
      on:
        tags: true